name: Build

on:
  push:
    branches:
      - build/*

jobs:

  build-number:
    name: Generate build number
    runs-on: macOS-latest
    timeout-minutes: 5
    steps:
      - name: Generate build number
        run: echo `date +"%y%m%d%H%M"` >> build-number.txt
      - name: Upload artifact with build number
        uses: actions/upload-artifact@v1
        with:
          name: build-number
          path: build-number.txt

  build-alpha:
    name: Create Alpha build
    needs: build-number
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Download artifact with build number
        uses: actions/download-artifact@v1
        with:
          name: build-number
      - name: Setup access to Twine repo and pull
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY_TWINE }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          TWINE_FOLDER: ~/twine
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          git clone "git@github.com:MateeDevs/twine-localization.git" $TWINE_FOLDER
      - name: Create a new Alpha build
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY_MATCH }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          TWINE_FOLDER: ~/twine
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          CI: ${{ true }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          bundle install --path vendor/bundle
          bundle exec pod install --repo-update
          bundle exec fastlane build_alpha git_branch:$GITHUB_REF build_number:`cat build-number/build-number.txt`
      - name: Upload the Alpha build to the TestFlight
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: bundle exec fastlane upload_testflight_alpha

  build-beta:
    name: Create Beta build
    needs: build-number
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Download artifact with build number
        uses: actions/download-artifact@v1
        with:
          name: build-number
      - name: Setup access to Twine repo and pull
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY_TWINE }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          TWINE_FOLDER: ~/twine
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          git clone "git@github.com:MateeDevs/twine-localization.git" $TWINE_FOLDER
      - name: Create a new Beta build
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY_MATCH }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          TWINE_FOLDER: ~/twine
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          CI: ${{ true }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          bundle install --path vendor/bundle
          bundle exec pod install --repo-update
          bundle exec fastlane build_beta git_branch:$GITHUB_REF build_number:`cat build-number/build-number.txt`
      - name: Upload the Beta build to the TestFlight
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: bundle exec fastlane upload_testflight_beta

  # build-production:
  #   name: Create Production build
  #   needs: build-number
  #   runs-on: macOS-latest
  #   timeout-minutes: 60
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v1
  #     - name: Download artifact with build number
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: build-number
  #     - name: Setup access to Twine repo and pull
  #       env:
  #         DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY_TWINE }}
  #         GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
  #         TWINE_FOLDER: ~/twine
  #       run: |
  #         eval "$(ssh-agent -s)"
  #         ssh-add - <<< "${DEPLOY_KEY}"
  #         git clone "git@github.com:MateeDevs/twine-localization.git" $TWINE_FOLDER
  #     - name: Create a new Production build
  #       env:
  #         DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY_MATCH }}
  #         GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
  #         TWINE_FOLDER: ~/twine
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  #         CI: ${{ true }}
  #       run: |
  #         eval "$(ssh-agent -s)"
  #         ssh-add - <<< "${DEPLOY_KEY}"
  #         bundle install --path vendor/bundle
  #         bundle exec pod install --repo-update
  #         bundle exec fastlane build_production git_branch:$GITHUB_REF build_number:`cat build-number/build-number.txt`
  #     - name: Upload the Production build to the TestFlight
  #       env:
  #         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  #       run: bundle exec fastlane upload_testflight_production
