name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (x.x.x)'     
        required: true

jobs:
  build:
    name: Create new builds
    runs-on: [self-hosted, ios-build]
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Pull Twine repo
        run: git -C $TWINE_FOLDER pull origin master
      - name: Setup tools
        run: ./scripts/setup.sh
      - name: Generate version and build numbers
        run: |
          echo "VERSION_NUMBER=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$(echo `date +"%y%m%d%H%M"`)" >> $GITHUB_ENV
      - name: Create a new Alpha build
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        run: fastlane build_alpha
      # - name: Create a new Beta build
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      #     APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
      #   run: fastlane build_beta
      # - name: Create a new Production build
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      #     APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
      #   run: fastlane build_production
      - name: Create and push git tag
        run: |
          git tag "$VERSION_NUMBER.$BUILD_NUMBER"
          git push origin "$VERSION_NUMBER.$BUILD_NUMBER"

  deploy-alpha:
    name: Deploy alpha
    needs: build
    runs-on: [self-hosted, ios-alpha]
    timeout-minutes: 600
    steps:
      - name: Upload the Alpha build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        run: fastlane upload_testflight_alpha

  # deploy-beta:
  #   name: Deploy beta
  #   needs: build
  #   runs-on: [self-hosted, ios-beta]
  #   timeout-minutes: 600
  #   steps:
  #     - name: Upload the Beta build to the TestFlight
  #       env:
  #         APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
  #         SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
  #       run: fastlane upload_testflight_beta

  # deploy-production:
  #   name: Deploy production
  #   needs: build
  #   runs-on: [self-hosted, ios-prod]
  #   timeout-minutes: 600
  #   steps:
  #     - name: Upload the Production build to the TestFlight
  #       env:
  #         APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
  #         SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
  #       run: fastlane upload_testflight_production
