name: Build

on:
  push:
    branches:
      - build/*

jobs:

  build:
    name: Create new builds
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Pull Twine repo
        run: git -C $TWINE_FOLDER pull origin master
      - name: Generate build number
        run: echo `date +"%y%m%d%H%M"` >> build-number.txt
      - name: Install Gems and Pods
        env:
          CI: ${{ true }}
        run: ./scripts/setup.sh
      - name: Create a new Alpha build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane build_alpha git_branch:$GITHUB_REF build_number:`cat build-number.txt`
      # - name: Create a new Beta build
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      #   run: bundle exec fastlane build_beta git_branch:$GITHUB_REF build_number:`cat build-number.txt`
      # - name: Create a new Production build
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      #   run: bundle exec fastlane build_production git_branch:$GITHUB_REF build_number:`cat build-number.txt`

  deploy-alpha:
    name: Deploy alpha
    needs: build
    runs-on: self-hosted
    timeout-minutes: 600
    steps:
      - name: Upload the Alpha build to the TestFlight
        env:
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: |
          bundle exec fastlane upload_testflight_alpha
          bundle exec fastlane dsym_alpha

  # deploy-beta:
  #   name: Deploy beta
  #   needs: build
  #   runs-on: self-hosted
  #   timeout-minutes: 600
  #   steps:
  #     - name: Upload the Beta build to the TestFlight
  #       env:
  #         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  #       run: |
  #         bundle exec fastlane upload_testflight_beta
  #         bundle exec fastlane dsym_beta

  # deploy-production:
  #   name: Deploy production
  #   needs: build
  #   runs-on: self-hosted
  #   timeout-minutes: 600
  #   steps:
  #     - name: Upload the Production build to the TestFlight
  #       env:
  #         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  #       run: |
  #         bundle exec fastlane upload_testflight_production
  #         bundle exec fastlane dsym_production
