name: Build

on:
  push:
    branches:
      - build/*

jobs:
  build:
    name: Create new builds
    runs-on: [self-hosted, ios-build]
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          clean: false
      - name: Pull Twine repo
        run: git -C $TWINE_FOLDER pull origin master
      - name: Install Gems and Pods
        env:
          CI: ${{ true }}
        run: ./scripts/setup.sh
      - name: Generate build number
        run: |
          echo "BUILD_NUMBER=$(echo `date +"%y%m%d%H%M"`)" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(echo $GITHUB_REF)" >> $GITHUB_ENV
      - name: Create a new Alpha build
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
        run: bundle exec fastlane build_alpha
      # - name: Create a new Beta build
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      #     APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
      #   run: bundle exec fastlane build_beta
      # - name: Create a new Production build
      #   env:
      #     MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      #     APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
      #   run: bundle exec fastlane build_production

  deploy-alpha:
    name: Deploy alpha
    needs: build
    runs-on: [self-hosted, ios-alpha]
    timeout-minutes: 600
    steps:
      - name: Upload the Alpha build to the TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
          SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
        run: bundle exec fastlane upload_testflight_alpha

  # deploy-beta:
  #   name: Deploy beta
  #   needs: build
  #   runs-on: [self-hosted, ios-beta]
  #   timeout-minutes: 600
  #   steps:
  #     - name: Upload the Beta build to the TestFlight
  #       env:
  #         APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
  #         SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
  #       run: bundle exec fastlane upload_testflight_beta

  # deploy-production:
  #   name: Deploy production
  #   needs: build
  #   runs-on: [self-hosted, ios-prod]
  #   timeout-minutes: 600
  #   steps:
  #     - name: Upload the Production build to the TestFlight
  #       env:
  #         APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_MATEE }}
  #         SLACK_URL: ${{ secrets.FASTLANE_SLACK_URL }}
  #       run: bundle exec fastlane upload_testflight_production
